C:\ProgramData\Oracle\Java\javapath;
C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\iCLS\;
C:\Program Files\Intel\Intel(R) Management Engine Components\iCLS\;
C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;
C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\Intel\UCRT\;
C:\Program Files\Intel\UCRT\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;
C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;
C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;
C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\WiFi\bin\;
C:\Program Files\Common Files\Intel\WirelessCommon\;
C:\Program Files\dotnet\;
C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;
C:\Program Files (x86)\GtkSharp\2.12\bin;
C:\Program Files\PuTTY\;
C:\Program Files\Git\cmd;
%JAVA_HOME%\bin;
C:\Tomcat\bin;

%JAVA_PATH&;%Intel%;%DOTNET%;%MSSQL%;%GTK%;%PUTTY%;%GIT%;%POWERSHELL%;C:\Tomcat\bin;%JAVA_HOME%\bin;